name: 'Comment on PR'
description: 'This action comments on a pull request with a default message'
inputs:
  repo-token:
    description: 'Token to use to comment on the PR'
    required: true
  pr-number:
    description: 'The number of the pull request'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: 'Check for .tf files'
      id: check_tf_files
      shell: bash
      run: |
        if git ls-files '*.tf' | grep -q .; then
          echo "TERRAFORM_FILES_FOUND=true" >> $GITHUB_ENV
        else
          echo "TERRAFORM_FILES_FOUND=false" >> $GITHUB_ENV
        fi
        
    - name: Set up Node.js
      if: env.TERRAFORM_FILES_FOUND == 'true'
      uses: actions/setup-node@v4
      with:
        node-version: '22.4.1'
        
    - name: Comment on PR
      shell: bash
      run: |
        curl -X POST -H "Authorization: token ${{ inputs.repo-token }}" \
        -H "Content-Type: application/json" \
        -d '{"body":"Hello World"}' \
        "https://api.github.com/repos/${{ github.repository }}/issues/${{ inputs.pr-number }}/comments"
