name: 'Snyk Scan'
description: 'This action comments on a pull request with a default message'

inputs:
  repo-token:
    description: 'Token to use to comment on the PR'
    required: true
  snyk-token:
    description: 'Token to use Snyk'
    required: true
  pr-number:
    description: 'The number of the pull request'
    required: true
  message:
    description: 'The message to comment on the pull request'
    required: true
    default: 'Hello World'


permissions:
  contents: read
  issues: write
  pull-requests: write


runs:

  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: 'Check for .tf files'
      id: check_tf_files
      shell: bash
      run: |
        if git ls-files '*.tf' | grep -q .; then
          echo "TERRAFORM_FILES_FOUND=true" >> $GITHUB_ENV
        else
          echo "TERRAFORM_FILES_FOUND=false" >> $GITHUB_ENV
        fi

    - name: Set up Node.js
      if: ${{ env.TERRAFORM_FILES_FOUND == 'true' }}
      uses: actions/setup-node@v4
      with:
        node-version: '22.4.1'

    - name: 'Install Snyk CLI'
      if: ${{ env.TERRAFORM_FILES_FOUND == 'true' }}
      shell: bash
      run: npm install -g snyk

    - name: 'Authenticate Snyk'
      if: ${{ env.TERRAFORM_FILES_FOUND == 'true' }}
      shell: bash
      env:
        SNYK_TOKEN: ${{ inputs.snyk-token }}
      run: snyk auth $SNYK_TOKEN
      
      - name: Run Snyk Test
        id: snyk-test
        if: ${{ env.TERRAFORM_FILES_FOUND == 'true' }}
        run: |
          snyk iac test > snyk_output.txt || true
          echo "Snyk test output:"
          cat snyk_output.txt
          TEST_OUTPUT=$(cat snyk_output.txt)
          echo "SNYK_TEST_OUTPUT<<EOF" >> $GITHUB_ENV
          echo "${TEST_OUTPUT}" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
          echo "Test output captured."
          
      - name: Check if Snyk Test Output is Empty
        run: |
          if [ -z "${{ env.SNYK_TEST_OUTPUT }}" ]; then
            echo "Snyk test output is empty. Exiting."
            exit 1
          fi


      - name: Use Pull Request Decoration Action
        if: ${{ env.SNYK_TEST_OUTPUT != '' }}
        uses: douglasmendeslda/gha-pull-request-decoration@v1.1
        with:
          message: ${{ env.SNYK_TEST_OUTPUT }}
        env:
          GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}
          GITHUB_REPOSITORY_NAME: ${{ github.event.pull_request.head.repo.name }}
          GITHUB_PR_NUMBER: ${{ github.event.pull_request.number }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}