name: 'Comment on PR'
description: 'This action comments on a pull request with a default message'
inputs:
  repo-token:
    description: 'Token to use to comment on the PR'
    required: true
  snyk-token:
    description: 'Token to use Snyk'
    required: true
  pr-number:
    description: 'The number of the pull request'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: 'Check for .tf files'
      id: check_tf_files
      shell: bash
      run: |
        if git ls-files '*.tf' | grep -q .; then
          echo "TERRAFORM_FILES_FOUND=true" >> $GITHUB_ENV
        else
          echo "TERRAFORM_FILES_FOUND=false" >> $GITHUB_ENV
        fi
        
    - name: Set up Node.js
      if: ${{ env.TERRAFORM_FILES_FOUND == 'true' }}
      uses: actions/setup-node@v4
      with:
        node-version: '22.4.1'

    - name: 'Install Snyk CLI'
      if: ${{ env.TERRAFORM_FILES_FOUND == 'true' }}
      shell: bash
      run: npm install -g snyk

    - name: 'Authenticate Snyk'
      if: ${{ env.TERRAFORM_FILES_FOUND == 'true' }}
      shell: bash
      env:
        SNYK_TOKEN: ${{ inputs.snyk-token }}
      run: snyk auth $SNYK_TOKEN
      
    - name: 'Run Snyk IaC Test'
      if: ${{ env.TERRAFORM_FILES_FOUND == 'true' }}
      id: run_snyk_test
      shell: bash
      run: |
        snyk iac test > snyk_output.txt || true
        echo "Snyk test output:"
        cat snyk_output.txt
        TEST_OUTPUT=$(cat snyk_output.txt)
        echo "SNYK_TEST_OUTPUT<<EOF" >> $GITHUB_ENV
        echo "${TEST_OUTPUT}" >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV
        echo "Test output captured."
        
    - name: Comment on PR
      if: ${{ env.TERRAFORM_FILES_FOUND == 'true' }}
      shell: bash
      env:
        SNYK_TEST_OUTPUT: ${{ steps.run_snyk_test.outputs.SNYK_TEST_OUTPUT }}
      run: |
        curl -X POST -H "Authorization: token ${{ inputs.repo-token }}" \
        -H "Content-Type: application/json" \
        -d '{"body":"'"${SNYK_TEST_OUTPUT}"'"}' \
        "https://api.github.com/repos/${{ github.repository }}/issues/${{ inputs.pr-number }}/comments"
